# Site settings
title: Qing Ji
email: qingji@stanford.edu
description: Personal academic webpage of Ji, Qing
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
    Qing Ji (纪晴)<br/>
    PhD student in Geophysics<br/>
    Stanford University

location: >
  Department of Geophysics<br/>
  Doerr School of Sustainability<br/>
  Stanford University

contact: >
    <a href="mailto:qingji@stanford.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Email: qingji@stanford.edu</a> <br/>
    <a href="https://github.com/NickJi98" target="_blank"><i style="font-size:19px" class="fa">&#xf092;</i> GitHub</a>
    

# Pages shown in navbar
nav_pages:
  - name: CV
  - name: Publications
  - name: Research

include:
  - .htaccess
  - _pages
  - _data


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Ji
  first_name: Qing

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"
  
  bibtex_skip_fields: [abstract, month_numeric, github]

exclude:
  - Gemfile
  - Gemfile.lock
  - update_bootstrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
